### ISSUE TITLE
Automate pulling Miovision data from API

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#101]
Also relevant to #99

**Comment by rickl4** [comment]
As the number of days pulled from the API increases, the processing time increases. Specifically, the main source of the increase is the aggregation into 15 minute bins which increases linearly. Currently, the size of the raw data table is around 60,000,000 rows, about 3x the size of `miovision.raw_data`.

![image004](https://user-images.githubusercontent.com/38917106/43975181-c673148a-9caa-11e8-8390-b3e1c0dbb8d4.png)
![image002](https://user-images.githubusercontent.com/38917106/43975186-c9d1ad08-9caa-11e8-9796-60e9325668da.png)

Another issue I didn't forsee was the time taken to refresh the views. Originally, they were done as the very last step, but the amount of data in the tables makes it become a long process. I'm going to change the process so that the views are updated after each day of data is pulled, and investigate adding indexes to the views

**Comment by rickl4** [comment]
Additionally, theres been sporadic instances of a 504 Gateway timeout error thats not documented in the API documentation. Retrying will successfully grab the data. Unlike the 500 error which was caused by having invalid date ranges, this error is not easily replicable. I'll try to mitigate this in the code, but its hard to test for since I'm not seeing a pattern to this error.

**Comment by rickl4** [comment]
Currently, all the data from March 1st until now is pulled into the `miovision_api` schema.

Before March 1st, only 5-10 days had data in a month. In addition, some days has approximately 400,000 rows, or about 10x the normal amount of data, which causes the query to hang.

**Comment by radumas** [comment]
API script is working fine. Some improvements are being worked on in #135 and #143

**Comment by radumas** [comment]
Minor issue: the help text for some of the parameters was copy-pasted and not updated for those options
https://github.com/CityofToronto/bdit_data-sources/blob/f99bc84513d3fb9adaaab89a7bbe7e4fc1f281f9/volumes/miovision/api/intersection_tmc.py#L73-L75
