### ISSUE TITLE
Add non-downtown Blip routes to segments table

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#102]
There are ~100 routes from other travel time studies that could be added to the `segments` table for the Open Data Release. Unfortunately their coordinates do not appear under `route_points` in `bluetooth.all_analyses`. I've asked vendor about this missing information and meanwhile, Quin sent over the Google Map of the sensor locations, so will use these locations to start sketching the routes.
 - [x] import sensor location kml into database
 - [x] first join of these locations with the centerline file
 - [x] fill in cross street information
 - [ ] validate.

**Comment by rickl4** [comment]
Currently, I made lines, following the centreline network, connecting each of the new readers together. This is currently in `rliu.new_bt_segments`. 

This is a sample of the format:

|analysis_id | corridor   | from_intersection         | from_long | from_lat| to_intersection   | to_long | to_lat | geo_id array                                                                                                                                                                                                                             |centreline street name array               | geom string                                    | length  |
|---------|---------------|-----------------|-------------|------------|-----------------|-------------|------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|
| 1448391 | Consumers     | IBM             | -79.3310523 | 43.7704895 | Herons Hill Way | -79.3352044 | 43.77556   | {438154,438172,438289,438551,438653,30013036}                                                                                                                                                                                                                          | {Consumers Rd","Sheppard Ave E"}"                 | 0102000020E61000001E00000038C23FF872D553C0CBA4745344E345400FB75F1872D553C0668C6F2544E34540CAADAEE26BD553C010AB81DE42E3454030639D396AD553C07F4C3B9A42E34540D2C40B875DD553C0895CCE7740E345408999D31E3CD553C06F3427FF38E34540F6AF7CFB32D553C0B5189F7636E34540D4AC9E (...) | 883  |
| 1448474 | Morningside   | 401Morn         | -79.1979611 | 43.7979015 | Meadowvale      | -79.1705489 | 43.8082543 | {104501,104610,104870,3829223,4512390,5439765,13975237,14660466,14660467,20154540,20154541,20154558,30002406,30002407,30019841,30019842}                                                                                                                               | {Morningside Ave","Sheppard Ave E"}"              | 0102000020E61000001E000000F00BB2DCA7CC53C073C42C441FE6454065B02672A8CC53C0574CF32E21E6454062B44A8DA9CC53C0298E57AE24E64540F1E709BBB0CC53C0796343623BE6454099E7F8D0B4CC53C0286CF58B48E64540BF8A638FB6CC53C0995731394EE64540518CD3E0BBCC53C0BFF72FF766E64540714158 (...) | 2926 |

My next steps are to:
* Create a field for the direction of each corridor by using the from/to cordinates
* Format the table so that it can be easily inserted to `bluetooth.corridors`

**Comment by radumas** [comment]
For the first next step, `gis.direction_from_line(line)` could be useful.

**Comment by rickl4** [comment]
I created a view `rliu.bluetooth_insert` with the new corridors properly formatted and ready to be inserted into `bluetooth.segments`. I made sure the directions of the lines matched the direction of the corridor.

**Comment by rickl4** [comment]
`rliu.new_bt_readers` is also updated with the new detectors and formatted to match `bluetooth.detectors`.

**Comment by radumas** [comment]
Just found the same segment_name appearing twice in the dataset, with different `analysis_id`s

![image](https://user-images.githubusercontent.com/10623872/48091086-bfaf7c80-e1d6-11e8-98d2-8fe1ea6ede8d.png)

(this is the only one).

**Comment by rickl4** [comment]
I looked at `bluetooth.all_analyses` and there seems to be 2 routes with similar names. I also made sure that it wasn't a southbound route that got improperly named (it wasn't and 1428150 is the southbound route).

![image](https://user-images.githubusercontent.com/38917106/48091778-aa3b5200-e1d8-11e8-901e-ca14bf51c55e.png)

I think removing one of the duplicate routes from `rliu.new_bluetooth_segments` is probably the best solution. There aren't any readers named `AS2` on Quin's map so I think deleting `1427570` may be better.

**Comment by radumas** [comment]
Trying to identify potential mismatches in intersection naming, the below query shows streets which have a different start/end name and 
```sql
WITH intersections as (SELECT row_number() OVER() int_id, x_section 
					   FROM (SELECT (string_to_array(segment_name, '_'))[1:2] as x_section
							  FROM rliu.bluetooth_update
							  UNION
							  SELECT (string_to_array(segment_name, '_'))[3:4] as end_intersect
							  FROM rliu.bluetooth_update) x_section_union
					  )
, flipped_xsections as(SELECT a.x_section, b.x_section AS reversed_x_section
FROM intersections a
INNER JOIN intersections b ON a.x_section != b.x_section AND a.x_section = ARRAY[b.x_section[2], b.x_section[1]] AND a.int_id < b.int_id--Are not equal but have the same two cross_streets
)
SELECT array_to_string(x_section, '_')||'<->'||array_to_string(reversed_x_section, '_') As reversal,
bluetooth_update.*
FROM flipped_xsections
INNER JOIN rliu.bluetooth_update ON segment_name LIKE '%'||array_to_string(x_section, '_')||'%' OR segment_name LIKE '%'||array_to_string(reversed_x_section, '_')||'%'
WHERE (string_to_array(segment_name, '_'))[1] != (string_to_array(segment_name, '_'))[3]
```

reversal|segment_name|analysis_id|street|direction|start_crossstreet|end_crossstreet
|-------|-----------------|-----------|------|-----------|-----------------|------------------|
'MO_SH<->SH_MO'|'MO_SH_MI_MU'|'1448655'|'Morningside'|'SB'|'Sheppard'|'Murison'
'MO_SH<->SH_MO'|'MI_MU_SH_MO'|'1448463'|'Milner'|'EB'|'Murison'|'Morningside'
'MO_SH<->SH_MO'|'BR_WI_SH_MO'|'1448385'|'Brenyon'|'EB'|'Wickson'|'Morningside'
'SH_VP<->VP_SH'|'SH_VP_CN_IB'|'1448851'|'Sheppard'|'WB'|'Victoria Park'|'IBM'
'SH_VP<->VP_SH'|'CN_IB_SH_VP'|'1448408'|'Consumers'|'EB'|'IBM'|'Victoria Park'

The two Sheppard & Vic Park should have the abbreviations flipped, since the route starts/ends on Vic Park @ Sheppard and not the converse.
`MI_MU_SH_MO` should have the end intersection reversed to Morningside @ Sheppard, and is also missing the Morningside segment in the route.
That last inspired a check to see if the intersections of the reversed lines were equivalent:
```sql
SELECT a.analysis_id, a.segment_name, b.analysis_id, b.segment_name
FROM rliu.bluetooth_update a											  
INNER JOIN rliu.bluetooth_update b ON a.geom = ST_Reverse(b.geom)
WHERE a.analysis_id <> b.analysis_id AND ((string_to_array(a.segment_name, '_'))[1:2] != (string_to_array(b.segment_name, '_'))[3:4]
OR (string_to_array(a.segment_name, '_'))[3:4] != (string_to_array(b.segment_name, '_'))[1:2])
```

Previously highlighted issues were raised as well as:
|analysis_id|segment_name|analysis_id|segment_name|
|----------|------------------|-----------|-------------------|
'1448463'|'MI_MU_SH_MO'|'1448547'|'MO_MI_MI_MU'
'1448463'|'MI_MU_SH_MO'|'1448457'|'MI_MU_MO_MI'

**Comment by radumas** [comment]
## Route lengths match

Investigating whether routes with same intersections (ish) have the same lengths
```sql
SELECT a.analysis_id, a.segment_name, a.length, b.analysis_id, b.segment_name, b.length
FROM rliu.bluetooth_update a											  
INNER JOIN rliu.bluetooth_update b ON  a.analysis_id < b.analysis_id AND array_sort(string_to_array(a.segment_name, '_')) = array_sort(string_to_array(b.segment_name, '_'))
WHERE abs(a.length - b.length) > 20
```

I only left what seemed to be errors in the below table, and added comments from reviewing in QGIS

a.analysis_id|a.segment_name|a.length|b.analysis_id|b.segment_name|b.length|comment|
|------------|-------------------|---------|--------------|------------------|---------|-----------|
'1448552'|'MO_MI_SH_MU'|'793'|'1448700'|'SH_MU_MO_MI'|'1297'|First route missing a segment|
'1448552'|'MO_MI_SH_MU'|'793'|'1448463'|'MI_MU_SH_MO'|'301'|Second route missing Morningside segment|
'1448730'|'SH_NE_MO_MI'|'1699'|'1448557'|'MO_MI_SH_NE'|'1999'|Second route includes segment to MI_MU|
'1448773'|'SH_SE_VP_401'|'924'|'1448831'|'VP_401_SH_SE'|'976'|First route missing final segment to 401|
'1448805'|'SH_VP_SH_SE'|'751'|'1448794'|'SH_SE_SH_VP'|'674'|Both are wrong in this case|
'1448911'|'YO_GL_BL_MP'|'860'|'1448368'|'BL_MP_YO_GL'|'1101'| I think the latter has an extra segment to GL_DP|

**Comment by radumas** [comment]
2.5 outstanding issues

## `MI_MU_SH_MO` 

missing a section if it's supposed to go to Morningside and Sheppard
![image](https://user-images.githubusercontent.com/10623872/48785757-5be78200-ecb3-11e8-8be9-3931f79036c4.png)

## Sheppard and Morningside

Two routes tagged with Sheppard and Morningside are actually at Sheppard and Vic Park

![image](https://user-images.githubusercontent.com/10623872/48787248-6c4d2c00-ecb6-11e8-83fc-ebf8b5a0843d.png)
