### ISSUE TITLE
Removing non-service stops from processing

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#126]
There are stops for the streetcar routes that are not actual stops, but labelled intersections for (probably) timing purposes, these can be filtered with the `pickup_type` and `drop_off_type` values in `stop_times` ([ref](http://gtfs.org/reference/#stop_times_7))

**Comment by chelsrosic** [comment]
Removing the non-service stops did not lead to a dramatic decrease in very short trips, which is what we expected to happen. Many trips with very long and very short lengths exist after the non service stops were removed. This demonstrates the fact that more processing must be done in order to make sure that there are no incorrectly identified trips. 

![remove_non_service_514](https://user-images.githubusercontent.com/32607196/42290448-4953139e-7f93-11e8-8d79-6c3814d5748d.PNG)
![remove_non_service_504](https://user-images.githubusercontent.com/32607196/42290454-4e476940-7f93-11e8-9dcb-2ba1f596c907.PNG)

**Comment by chelsrosic** [comment]
The length that trips should be and the amount of trips at this length in a day according to the GTFS data. 

```sql
WITH step_1 AS(SELECT route_short_name, trip_id, count(1) as length
  FROM gtfs_raph.stop_times_20171004_504_514

GROUP BY route_short_name, trip_id
)
SELECT route_short_name, length, count(1)
FROM step_1
GROUP BY route_short_name, length
ORDER BY route_short_name, length DESC; 
```

Output: 

'route_short_name'|'length'|'count'
--- | --- | ---
'504'|65|276
'504'|59|271
'504'|58|4
'504'|53|1
'504'|50|2
'504'|14|13
'504'|12|22
'504'|11|20
'504'|10|16
'514'|39|93
'514'|37|101
'514'|33|9
'514'|30|1

**Comment by radumas** [comment]
Oops, that query is with all the stops in... which wasn't the point of this issue :man_facepalming:
