### ISSUE TITLE
Migrate Blip API Script to use psycopg2 module

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#131]
Used `pygresql` instead of `psycogp2` to develop `blip_api.py` because of installation issues with `psycopg2` on the Windows terminal server (lack of a postgresql binary IIRC).

But I accidentally used the more... unique version of `pygresql`, which won't be as interchangeable as the [DB-API compliant version](http://www.pygresql.org/contents/pgdb/index.html), which should have a very similar API to `psycopg2`

**Comment by radumas** [comment]
Workaround...

The PygreSQL [installation instructions](http://www.pygresql.org/contents/install.html) read

>On Windows, this library is called libpq.dll and is for instance contained in the PostgreSQL ODBC driver (search for “psqlodbc”).

Navigated to the [downloads page for psqlodbc](https://www.postgresql.org/ftp/odbc/versions/) and selected the MSI option. I downloaded the latest one for PostgreSQL 9.

**Comment by chmnata** [comment]
Switched everything except for an upsert command and a json encode step, which require a little more work since I will have to construct the sql for upsert, and check the result of encoding the json. 

Documentation for pg db's upsert. 
http://www.pygresql.org/contents/pg/db_wrapper.html#pg.DB.upsert

pygresql's json encoder
http://www.pygresql.org/contents/pg/db_wrapper.html#encode-decode-json-encode-and-decode-json-data
>This is the same as the json.dumps() function from the standard library.
I will probably just use json.dumps from json

psycopg2 have some sort of json adaptation
https://www.psycopg.org/docs/extras.html#json-adaptation

**Comment by chmnata** [comment]
tested the script out with with blip backfill and backfilled date 2022-03-22, now backfilling 22 to 28.
