### ISSUE TITLE
Debugging why CIS-TTC comparison results in ~2x processed data 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#134]
While working on #130, comparing the data from trip segments on the 514 & 504 between our CIS processing and the processing the TTC have done, we have run into the issue of having approximately 2x the number of trip-segments from our process CIS data vs. the TTC's.

To debug this we should first identify whether running [our process on CIS for a week of data](https://github.com/CityofToronto/bdit_data-sources/blob/6740910a8f460a0aec5d2ba221c1c92fd9396b1f/ttc/sql/process_nov_19_25.sql) has produced the expected amount of output. 
- [x] Count volume of data produced for each processed November day with previously processed 1 weekday of data.
- [ ] Recreate heatmap from the [validating CIS processing notebook](https://github.com/CityofToronto/bdit_data-sources/blob/0563a42a120a0d7fb712cd377c998efa362b3cdc/ttc/validating_cis_processing.ipynb) for a sample weekday in November

e.g.: 
![image](https://user-images.githubusercontent.com/10623872/43546180-f6da7f16-95a5-11e8-91aa-a07907409c70.png)

**Comment by radumas** [comment]
Per [above :point_up:](https://github.com/CityofToronto/bdit_data-sources/blob/4ebcb72c064fa42109d5be111dd649fd527ca043/ttc/debugging_cis_ttc_comparison.ipynb) issue is in [this query](https://github.com/CityofToronto/bdit_data-sources/blob/cis_data/ttc/sql/process_nov_19_25.sql#L89-L138), possibly because of using different number of shapes than in [original query](https://github.com/CityofToronto/bdit_data-sources/blob/cis_data/ttc/cis_processing.md#step-1--2)

**Comment by chelsrosic** [comment]
**What I've analyzed** 
At the bottom of the `debugging_cis_ttc_comparison` under the `Results from first fix` heading, I have analyzed the overall counts for the whole week between the segments provided from the TTC. I found that the cases are more similar to the TTC counts, however they are not exactly the same and I think the difference is still significant. For example, instead of having counts that are a few thousand off like they were before, the counts are about a few hundred off.  Our counts are always lower than theirs now, before they were larger. Additionally, the segments with subways as one of the endpoints have especially large differences in counts (for example 586 versus 8). 

**What I tried/changed** 
I knew that the subways had more than one stop_id associated with them but I did not take this into consideration when originally calculating counts in the analysis in the comparing_ttc_data notebook. I edited the `section_runs` table (the table with the TTC data)  by adding an extra column so I could include the extra stop_id(s) for the segments that have an endpoint(s) at a subway station. The counts at the bottom of the `debugging_cis_ttc_comparison` under the `Results from first fix` heading take into account the the fact that subways have more than one stop_id. The edits that I made did not have an impact on the counts.
