### ISSUE TITLE
How does only getting peak period data affect interpolation?

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#150]
- [x] Do descriptive analysis of bins which would be interpolated because we don't know if there's data before/after them.

**Comment by rickl4** [comment]
So since we started receiving only peak period data in May, there are 359,212 15 minute bins and 1661 bins were at the start/end of a period. 11 bins had interpolation either `TRUE` or `FALSE`, and 9 bins needed interpolation. Of those 9, 8 of them were did not have a bin before or after the bin, and were at the start or end of the period. The 2 bins that didn't need interpolation, were also at the start or end of the period. 

For the entire miovision schema, 4026 bins were at the start/end of a period, 1333 had interpolation being `TRUE` or `FALSE`. 146 of the 1333 bins were at the start/end of a period, and 85 needed interpolation and were at the start/end of a period. The majority of the bins where interpolation is `TRUE` or `FALSE` (885 out of 1333) occurred in October/November, but its not the case for the other cases (20 out of 146, 20 out of 85)

**Comment by aharpalaniTO** [comment]
Hey @rickl4 - mind summarizing the above information into a table?  Something like:

|  | Start/End of Period | Other Period |
| ------------- | ------------- | ------------- |
| Total Records  | 1,661  | 359,212 |
| Interpolation = TRUE  | X | Y |
| Interpolation = FALSE | X | Y |
| % Interpolated  | X | Y |

**Comment by rickl4** [comment]
For more background:
I used this query which aggregates and checks for interpolation on the `miovision.volumes` table. I looked at 3 time periods: October - December, January - April, and May - August. We've received data containing only peak periods (07:00-10:00 and 16:00-19:00) since the May csv dump.

```SQL
    DROP TABLE IF EXISTS bins;

    CREATE TEMPORARY TABLE bins (
            intersection_uid integer,
            datetime_bin timestamp without time zone,
            avail_minutes integer,
            start_time timestamp without time zone,
            end_time timestamp without time zone,
            previous_bin timestamp without time zone,
            previous_end timestamp without time zone,
            next_bin timestamp without time zone,
            next_start timestamp without time zone,
            interpolated boolean);
            
    WITH class_grouping AS (

        SELECT     intersection_uid, 
            datetime_bin as one_minute_bins,
            TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) AS datetime_bin,
            TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) - interval '1 minute' AS previous_bin,
            TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) + interval '15 minute' AS next_bin,
            TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) - interval '2 minute' AS previous_bin2,
            TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) + interval '16 minute' AS next_bin2
        FROM     miovision.volumes A
        WHERE     datetime_bin>'2018-05-01'
        GROUP BY intersection_uid, datetime_bin    
    ), bin_grouping AS(
        SELECT     intersection_uid, 
            datetime_bin, 
            COUNT(DISTINCT one_minute_bins) AS avail_minutes,
            min(one_minute_bins) as start_time,
            max(one_minute_bins) as end_time,
            lag(max(one_minute_bins)) OVER w as previous_end,
            lead(min(one_minute_bins)) OVER w as next_start,
            previous_bin,
            next_bin,
            previous_bin2,
            next_bin2,
            CASE WHEN  COUNT(DISTINCT one_minute_bins)<15 
                AND (NULLIF(next_bin, lead(min(one_minute_bins)) OVER w) IS NULL OR NULLIF(next_bin2, lead(min(one_minute_bins)) OVER w) IS NULL)
                AND (NULLIF(previous_bin, lag(max(one_minute_bins)) OVER w ) IS NULL OR NULLIF(previous_bin2, lag(max(one_minute_bins)) OVER w ) IS NULL) 
                THEN FALSE 
                ELSE NULL 
                END AS interpolated
        FROM class_grouping a
        GROUP BY intersection_uid, datetime_bin, previous_bin, next_bin, previous_bin2, next_bin2
        WINDOW w AS (PARTITION BY intersection_uid)
        ORDER BY intersection_uid, datetime_bin
    )

    INSERT INTO     bins
    SELECT         intersection_uid,
            datetime_bin,
            avail_minutes,
            start_time,
            end_time,
            previous_bin,
            previous_end,
            next_bin,
            next_start,
            interpolated
    FROM         bin_grouping
    WHERE (previous_bin - interval '15 minute' > previous_end) OR (next_bin + interval '15 minute' < next_start)
    AND avail_minutes>5
    ORDER BY intersection_uid, datetime_bin;

    UPDATE bins SET interpolated = FALSE WHERE (EXTRACT(minutes FROM end_time - start_time)+1) > avail_minutes AND avail_minutes < 15;
    UPDATE bins SET interpolated = TRUE WHERE interpolated IS NULL AND avail_minutes < 15;

    SELECT * 
    FROM        bins
    WHERE         interpolated IS NOT NULL
```

` WHERE (previous_bin - interval '15 minute' > previous_end) OR (next_bin + interval '15 minute' < next_start)` checks if the bin is at the start or end of a period, and `WHERE         interpolated IS NOT NULL` checks if interpolation is `FALSE` or `TRUE`

October - December

|  | Start/End of Period | Other Period |
| ------------- | ------------- | ------------- |
| Total Records  | 550  | 46,895|
| Interpolation = TRUE  | 48| 0 |
| Interpolation = FALSE | 10| 1055 |
| % Interpolated  | 8.73% | 0%

January - April

|  | Start/End of Period | Other Period |
| ------------- | ------------- | ------------- |
| Total Records  | 1,754  | 56,223 |
| Interpolation = TRUE  | 37| 8 |
| Interpolation = FALSE | 49| 116 |
| % Interpolated  | 2.11% | 0.01%|

May - August

|  | Start/End of Period | Other Periods |
| ------------- | ------------- | ------------- |
| Total Records  | 1,661  | 9,467 |
| Interpolation = TRUE  | 9| 0 |
| Interpolation = FALSE | 2| 0 |
| % Interpolated  | 0.54% | 0%|

Conclusions:
* Most bins that needed interpolation occurred at the start/end of period
* The proportion of bins that needed interpolation has gone down, and peak period data has caused proportion to go down further
* After receiving peak period data, the proportion of bins at a start/end of period has risen by almost 600%

Next steps:
* While we keep receiving csv dumps, I think we will get less potential false positives if we continued to check bins at the start/end of period for interpolation and do not change the interpolation process. These bins (16:00, 18:45, 7:00, 9:45) almost always have volume so any missing minutes is likely due to reader not working.

% of Bins in (16:00, 18:45, 7:00, 9:45)  that needed interpolation from October to April

|Bin  | Interpolation = FALSE| Interpolation = TRUE | No Interpolation
| ------------- | ------------- | ------------- |-------|
| 07:00  | 2  | 0| 1074
| 09:45 | 0| 0 |1368
| 16:00 | 0| 0 |1385
| 18:45 | 0 | 0|1385

* If possible, we should request Miovision give data from 15:45-19:15 and 06:45-10:15 inclusive.
