### ISSUE TITLE
Explore TTC Ridership data

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#199]
Goal of this is two-fold:

1. Create a schema/table structure to ingest TTC ridership data (available in HAN files) and stop info.

2. See if what has been provided is sufficient to determine ridership on TTC routes.

If we're OK, I'll ask for a dump of files for all routes.

**Comment by rickl4** [comment]
One problem I see is that the ridership data doesn't directly reference a stop_id or route_id, so without a lookup table, the spatial layer provided can not be linked. The stops in the ridership data are a "sort of" sequential series on the route (ex 505, stop 1 is Broadview), and not a unique code for each stop. Using GTFS data, I can infer the stop name and stop_id, seen in `rliu.ttc_stop_lookup`, but this method is imperfect because of the third problem.

The second problem is that the stops are not sequential in the ridership data. EX for the 505, there's no stop 2, or stop 47. If the stops were numbered sequentially, it would match the GTFS data, but right now, it doesn't.

The third problem is that the route number doesn't tell the full story for what stops the route has. I'm not confident that branches/short turns are reflected in the route field. The `improvised` field does not tell the short turn point/branch, so there's the possibility that we won't actually know the stop locations (without consulting the stop card excel file) if the route does not go the full length. 

In addition, the route_id field in GTFS is not unique to each branch/direction.

**Comment by rickl4** [comment]
Total boardings per day

```SQL
SELECT dt, route, dir,sum(boarding) FROM ttc_data_clean 
GROUP BY dt, route, dir
```

Boardings in the Peak Hour/Direction
```SQL
WITH hourly AS (

SELECT dt, extract(hour from tm) as hr,  route, dir,sum(boarding) as count FROM ttc_data_clean 
GROUP BY dt, route, dir, extract(hour from tm)
ORDER BY hr
), max AS (
SELECT max(count) as count, dt, route, dir
FROM hourly
GROUP BY dt,route, dir
)

SELECT count, dt, route, dir, hr
FROM max
LEFT JOIN hourly USING (dt, route, dir, count)
```

**Comment by rickl4** [comment]
For the stop card data we got, is it possible to request we get a data dictionary/lookup tables for each field? Some are obvious a lot aren't.

Also, could we get a new schema created for the data before they send us the data for all the routes?
