### ISSUE TITLE
Levenshtein distance can fail for streets that have E / W 

### ISSUE THREAD

**Issue by jovenc** [CityofToronto/bdit_data-sources#279]
For bylaw_id = 6667 where `highway` = "Welland Ave"	and `between` = "Lawrence Ave W and Douglas Avenue", it's routed as shown below and that is not right.  (highlighted is the road segment we want)
![image](https://user-images.githubusercontent.com/54872846/75817537-45a8ec80-5d65-11ea-8002-224badaa4278.png)

I found that the reason is that one of the intersection points found is not right. Running the function `gis._get_intersection_id` on "Welland Ave" and "Lawrence Ave W", I found the levenshtein distance below where int_id 13454250 is the one being chosen but int_id 134566028 is the right one. 
![image](https://user-images.githubusercontent.com/54872846/75817716-ac2e0a80-5d65-11ea-847d-9fcff01d9a6e.png)

Running a check on the `gis.centreline` table, I found this. 
![image](https://user-images.githubusercontent.com/54872846/75817896-f57e5a00-5d65-11ea-8838-cadd53e0a45b.png)

Since changing 'Lawrence Ave W' to 'Lawrence Ave E' only takes 1 step whereas changing 'Welland Ave' to 'Welland Rd' takes 3 steps, the intersection point with the less levenshtein distance is chosen instead, resulting in the segments of road that does not reflect the bylaws text.

I also found that when there are three street names in the `intersec5` column and two of the street names are almost the same with the slight change of E to W or vice versa (which happen particularly frequently for Yonge St like `Adelaide St E / Yonge St / Adelaide St W`, `King St E / Yonge St / King St W`, `Bloor St E / Yonge St / Bloor St W` etc), the intersection points found is weird because of the reason above.

_Originally posted by @jovenc in https://github.com/CityofToronto/bdit_data-sources/issues/271#issuecomment-594163276_

**Comment by jovenc** [comment]
This [comment](https://github.com/CityofToronto/bdit_data-sources/issues/268#issuecomment-596611959) might help in solving this problem too. Modifying the cost in pg_routing or adding emphasis on the street desired.

**Comment by radumas** [comment]
The problem is with the below line, which insures that at least two streets from the intersection are within a levenshtein distance of 4 of the input parameters, but it doesn't ensure that both input parameters are matched, rather than one being matched to multiple streets at that intersection, for example `Lawrence Ave W` getting matched to `Lawrence Ave W` and `Lawrence Ave E` or `Lawrence Ave W / Yonge St / Lawrence Ave E`

https://github.com/CityofToronto/bdit_data-sources/blob/text_to_centreline/gis/bylaw_text_to_centreline/sql/create-function-get_intersection_id_and_geom.sql#L29

**Comment by radumas** [comment]
Was this not fully resolved?
