### ISSUE TITLE
Make school zone pipeline resilient to text errors in the google sheet

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#438]
I think the ideal way is to have a PostgreSQL function for inserting data that reports errors and does upserts on the table and then loop over the sheet and send a Slack alert if an error occurred with a link to the log printout of all the erroneous rows.

**Comment by qu-xiang** [comment]
We have found that there are instances where:

- Same school_name can appear multiple times in the same year's table
- Same school_name can appear across different years' tables, but with different information in other fields

Sample SQL code, pull data from 2018/2019 tables
`WITH all_data AS (
    SELECT *, 2018 AS year FROM vz_safety_programs_staging.school_safety_zone_2018_raw
    UNION ALL
    SELECT *, 2019 AS year FROM vz_safety_programs_staging.school_safety_zone_2019_raw)
SELECT * FROM all_data
WHERE school_name IN (
    SELECT school_name FROM all_data
    GROUP BY school_name
    HAVING COUNT(*) > 1)
ORDER BY school_name;`

**Comment by tahaislam** [comment]
After testing the new validation rules (applied on columns: `locations_zone`, `inal_sign_installation`, `locations_fb`, `locations_wyss`), we found some outliers in previous years:

- 2018:
  - extra space preceding a decimal point in some coordinates _(can be fixed in our code if needed)_
    "F H MILLER JUNIOR PUBLIC SCHOOL; ST. NICOLAS OF BARI ELEMENTARY CATHOLIC SCHOOL"	"363 Rogers Rd;300 Caledonia Rd"	"9237848"		"43.683954, -79.458875; 43.682889, -79.460556"	"March 8, 2019"	"43.683016, -79.462317; 43.683212, -79.458610; 43.683297, -79.458100; 43.683431, -79.459481; 43.684938, -79.460248; **43 .685823**, -79.459249"	"43.684190, -79.458426"
- 2020:
  - missing decimal point in some coordinates _(can be fixed in our code if needed)_
    "ST BEDE CATHOLIC ELEMTARY SCHOOL"	"521 Sewell's Rd"	"10026267"	"10026269"	"43.8179875235, -79.2065508937"	"February 24, 2021"	"43.81745184469687, -79.20872942654107; 43.81873, **-79206048**"	"43.81768834878893, -79.20772756633532"
  - school outside Toronto (Markham)
    "ST EDWARD CATHOLIC ELEMENTARY SCHOOL"	"1 Botham Rd"	"10026965"	"10026967"	"**43.881563, -79.278362**"	"December 22, 2020"	"43.75446003841143, -79.41331804733053"	
- 2021:
  - FB outside Toronto (Markham)
    "ARMOUR HEIGHTS PUBLIC SCHOOL"	"148 Wilson Ave"	"10511844"	"10511846"	"43.74110004064953, -79.41949663080073"	"August 13, 2021"	"**43.88273950589168, -79.22172965771729**; 43.74109476174761, -79.41827007668574; 43.740008256247634, -79.42097734202389"	"43.740477834043425, -79.41938722162584; 43.74015626026105, -79.42000975953945"
  - Wrong sign & extra decimal point in FB location _(can be fixed in our code if needed)_
"ALPHA ALTERNATIVE JUNIOR SCHOOL"	"20 Brant St"	"10511898"	"10511900"	"43.645810278814096, -79.39816893080369"	"August 11, 2021"	"43.646361, -79.398167;  43.3844.7, **79.2402.0**"	"43.64577085765113, -79.39812982469044"
  - FB outside Toronto (New York)
"DOWNSVIEW PUBLIC SCHOOL"	"2829 Keele St"	"10511675"	"10511676"	"43.731534489186934, -79.48259367313007"	"August 16, 2021"	"43.72862159789891, -79.47805118582833; 43.729386, -79.481109; 43.72946593344107, -79.48231031121196; **40.61498127799897, -74.08772393430363**; 43.733921, -79.479723"	
  - FB points are separated by `,` instead of `;` _(can be fixed in our code if needed)_
"ST AGNES CATHOLIC ELEMENTARY SCHOOL"	"280 Otonabee Ave"	"10512824"	"10512825"	"43.79866062971354, -79.4026547307989"	"November 19, 2021"	"**43.8016856175515, -79.40383627387202, 43.802311819747466, -79.40184108736284**"

**Comment by tahaislam** [comment]
I ran the following query to get dependent objects (in our database) on `vz_safety_programs_staging.school_safety_zone_raw_parent` and there're only 3 columns being used so far (`school_name`, `locations_zone`, `final_sign_installation`):
```
SELECT dependent_ns.nspname as dependent_schema
, dependent_view.relname as dependent_view 
, source_ns.nspname as source_schema
, source_table.relname as source_table
, pg_attribute.attname as column_name
FROM pg_depend 
JOIN pg_rewrite ON pg_depend.objid = pg_rewrite.oid 
JOIN pg_class as dependent_view ON pg_rewrite.ev_class = dependent_view.oid 
JOIN pg_class as source_table ON pg_depend.refobjid = source_table.oid 
JOIN pg_attribute ON pg_depend.refobjid = pg_attribute.attrelid 
    AND pg_depend.refobjsubid = pg_attribute.attnum 
JOIN pg_namespace dependent_ns ON dependent_ns.oid = dependent_view.relnamespace
JOIN pg_namespace source_ns ON source_ns.oid = source_table.relnamespace
WHERE 
source_ns.nspname = 'vz_safety_programs_staging'
AND source_table.relname = 'school_safety_zone_raw_parent'
AND pg_attribute.attnum > 0;
```

Is there anyone else reading from this table directly?

**Comment by radumas** [comment]
Finding those dependents was a valiant attempt, but is missing the flow of data. Some of the elements in the spreadsheets end up in [vz_safety_programs.safetymeasures_points_new](https://github.com/Toronto-Big-Data-Innovation-Team/bdit_vz_programs/blob/master/_sql/aggregate/create-view-safetymeasures_points_new.sql) from [vz_safety_programs.safetymeasures_points](https://github.com/Toronto-Big-Data-Innovation-Team/bdit_vz_programs/blob/master/_sql/aggregate/create-view-safetymeasures_points.sql) and from:
* [`vz_safety_programs.points_flashing_beacons`](https://github.com/Toronto-Big-Data-Innovation-Team/bdit_vz_programs/blob/master/_sql/program_level/create-view-points_flashing_beacons.sql)
* [`vz_safety_programs.points_wyss`](https://github.com/Toronto-Big-Data-Innovation-Team/bdit_vz_programs/blob/master/_sql/program_level/create-view-points_wyss.sql)

**Comment by radumas** [comment]
You can see these data points showing up on the [Vision Zero Map](https://www.toronto.ca/services-payments/streets-parking-transportation/road-safety/vision-zero/safety-measures-and-mapping/)  
![image](https://user-images.githubusercontent.com/10623872/180053053-8d3c46a5-a11e-4d85-bdf5-1b642f6a4147.png)

**Comment by tahaislam** [comment]
The code is ready to be merged. But I was wondering if it's enough to just log the incorrect rows as errors or should there be a slack message sent out?
Note that some errors might be detected because of empty rows (could be skipped) or some rows showing some extra information which don't necessarily represent any school (can we just skip short rows?), such as:
```
[2022-07-21 11:53:18,832] {schools.py:240} ERROR - An error occurs at []
[2022-07-21 11:53:18,833] {schools.py:241} ERROR - list index out of range
[2022-07-21 11:53:18,833] {schools.py:240} ERROR - An error occurs at []
[2022-07-21 11:53:18,833] {schools.py:241} ERROR - list index out of range
[2022-07-21 11:53:18,833] {schools.py:240} ERROR - An error occurs at ['FOR TRACKING ONLY']
[2022-07-21 11:53:18,833] {schools.py:241} ERROR - list index out of range
[2022-07-21 11:53:18,833] {schools.py:240} ERROR - An error occurs at ['2017 SCHOOL SAFETY ZONES']
[2022-07-21 11:53:18,833] {schools.py:241} ERROR - list index out of range
```

**Comment by tahaislam** [comment]
Added a buffer to Toronto boundaries to skip one sign that is installed on the north side of Steeles. But found one last error in 2021. One point has lat and lon separated by `;` instead of `,`:


'ST MARCELLUS CATHOLIC ELEMENTARY SCHOOL; CENTRAL ETOBICOKE HIGH SCHOOL', '15 Denfield St', '2', 'Etobicoke', '10870996', '10511049', 'Initiated ', '', 'Initiated ', '', '', '', '', 'April 23, 2021', '', '', '', '', '', '', '', '', 'September 1, 2021', '', '43.67963161223461, -79.55435560196716; 43.67887288256282, -79.55541654153151', 'September 1, 2021', '43.67761499116308, -79.55686242739502; **43.678949608810505; -79.55229194343039**; 43.6798791564432, -79.55725587464416; 43.68131413390049, -79.55345203977507', '43.67924652072624, -79.55455544056552; 43.67997685854492, -79.55503019155573', 'End of Row'
