### ISSUE TITLE
Create a table of dubious dates for RESCU VDS Stations 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#573]
Similar to #570

**Comment by scann0n** [comment]
Here's what I've done so far:
1. Looked at continuous bin gap length >> `scannon.rescu_gaps_21`
2. Calculated gap frequency based on `scannon.rescu_gaps_21` and:
    - ~80% of the gaps were 1h 15 min or less (note - this looks like 1h 30 min in the data because bin start times are used (so the gap would start 15 minutes later than we think it does)
3. ID detectors with 91 bins per day instead of 96 >> `scannon.rescu_data_days_91`
4. Within those detectors, how many meet Raph’s transportation rules of thumb?
5. Made `scannon.rescu_dayvol_stats_21`
6. Used 20000 and 10000 as the “enough daily volume” thresholds; detectors and days with enough volume are in `scannon.rescu_enuf_vol`
7. Made a table that has all the detectors with 100 or more days of good data called `scannon.rescu_good_vol_days`

The branch is called i573_bad_rescu_dates; the sqls are in bdit_data-sources/volumes/rescu/date_evaluation!
