### ISSUE TITLE
Create a correct `speed_class` lookup in `traffic`

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#625]
- [ ] Create a correct `speed_class` lookup in `traffic` 
- [ ] Document it

`prj_volume.speed_classes` 

![image](https://github.com/CityofToronto/bdit_data-sources/assets/10623872/22ebd966-3887-42ba-8f1c-60f284a3c419)

does not match what is in MOVE 

https://github.com/CityofToronto/bdit_flashcrow/blob/a06291ea3c6dead31eef80af17f4de84f47d00dd/lib/Constants.js#L870-L885

nor does it match what is in the old traffic count software

![image](https://github.com/CityofToronto/bdit_data-sources/assets/10623872/9800f377-d2b1-45fc-a1ce-e97f5b7c51b4)

**Comment by radumas** [comment]
@dmcelro can you confirm the correct speed ranges for counts?

**Comment by radumas** [comment]
Confirmed that the latter is correct

**Comment by dmcelro** [comment]
The OTI data table is correct - looks like a mistake in the prj_volume.speed_classes - should be [0,20), [20,26), [26,30),[31,36), etc. (as stupid as that is - the ranges should probably actually be 1-20, 21-25, 26-30, 31-35 etc.)
The MOVE version looks the most correct - well, less confusing because I can never keep straight the difference between ) and ]:
[1, 19],
  [20, 25],
  [26, 30],
  [31, 35],
  [36, 40],
  [41, 45],
  [46, 50],
  [51, 55],
