### ISSUE TITLE
collisions_replicator.events take place in the future. 

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#643]
There are 38 collision events that take place in the future. 
```
SELECT COUNT(*) 
FROM collisions_replicator.events
WHERE accdate >= now()
```

**Comment by radumas** [comment]
This is very likely a Known Issue that'll get tackled by the Collision Core Dataset project, unless it seems like there is specifically an issue with the Mat View

**Comment by Nate-Wessel** [comment]
Rachel suggested a quick way of filtering these based on `accnb`, where the first two digits of the `accnb` would more reliably indicate the year. If the `accnb` is `20.*` then the year is very likely 2020 even if the date is 2029-etc  Though @Hanighomi wisely points out that it isn't right to just filter them out because they did actually happen - we just don't know when.

**Comment by mkewins** [comment]
The collision data team are aware of this issue, and it will be incorporated in our collision issue log and data pipeline work.
