### ISSUE TITLE
Partition aggregated Miovision volumes tables?

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#717]
I'm getting pretty bad performance while trying to query these tables (e.g. `miovision_api.volumes_15min_mvt` and `miovision_api.volumes_15min`) across all available dates. Even for a query that subsets the data to a single intersection and classification, which is indexed and should constitute a small subset of all data, I still see the query planner trying to do a full sequential scan in many (but not all) cases. I'm assuming this is because the data are inserted more or less sequentially, so the intersections and classifications aren't really clustered together on the disk and it knows it will have to read all the pages anyway. 

Wondering if a partition by classification and/or intersection would help performance here?

My thought it that a typical query would only hit a subset of classifications and intersections (and to be fair would likely have a limited date range as well).

Current unpartitioned tables sizes:
* `miovision_api.volumes_15min_mvt`: ~350m rows
* `miovision_api.volumes_15min`: ~278m rows

Sample query that seems like it really ought to be faster:
```sql
EXPLAIN SELECT 
    datetime_bin::date AS date,
    SUM(volume) AS count
FROM miovision_api.volumes_15min_mvt
WHERE
    intersection_uid = 2 -- indexed
    AND classification_uid = 2 -- also indexed
GROUP BY date
ORDER BY date
```

Or is there a better way of structuring this query?

**Comment by gabrielwol** [comment]
The fact that your query is not making use of the indices likely has to do with the volume of data you are selecting. Adding a date filter makes use of the unique constraint and runs in about 2s:
```sql
AND datetime_bin >= '2023-01-01'::date
```
If we partitioned by intersection (x68 distinct) and/or classification (x9 distinct), it would make queries that cut across those fields slower, so we'd have to weigh the different types of queries we make. Perhaps by classifications but grouped: cars, bikes, else?

**Comment by Nate-Wessel** [comment]
I think you're right. But here's some strangeness:

```sql
SELECT 
    datetime_bin::date AS date,
    SUM(volume) AS count
FROM miovision_api.volumes_15min_mvt
WHERE
    intersection_uid = 1 -- indexed
    AND classification_uid = 2 -- also indexed
    AND datetime_bin < '2021-01-01'
GROUP BY date
--ORDER BY date

UNION

SELECT 
    datetime_bin::date AS date,
    SUM(volume) AS count
FROM miovision_api.volumes_15min_mvt
WHERE
    intersection_uid = 1 -- indexed
    AND classification_uid = 2 -- also indexed
    AND datetime_bin >= '2021-01-01'
GROUP BY date
ORDER BY date
```

The above query takes about 5 seconds, while the original query took over 8 minutes. 

All the above does is split it into two parts (using an arbitrary date) and combine the results. But there has to be a better way of doing this...

**Comment by gabrielwol** [comment]
I propose: 
1) I think we should partition `miovision_api.volumes_15min` and `miovision_api.volumes_15min_mvt` by year since they both exceed 15GB. This will help with many of our common DRs as they query a small date slice of one of these tables. 
2) Adding summary tables (`volumes_daily`) grouped by date + classification (as above in Nate's query) could help for long time range queries, as these long range queries are unlikely to require disaggregate data. Daily summaries would help a lot on any sensor health checks (ie. are they working, are they reporting bike volumes). 
3) Change `volumes` table from inheritance to declarative partitioning. This will clean up the schema a bit when browsing and comes with some other improvements, like faster insert performance. Simultaneously we can partition volumes tables by month as they hover around 20GB for a year and data volume is only growing.

**Comment by radumas** [comment]
Just putting in writing that I approve of this plan
