### ISSUE TITLE
Miovision daily table should use a more standard definition of "day"

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#752]
The new `miovision_api.volumes_daily` table is really exciting! This could save me hours in updating the volumes index on a semi-regular basis and make large scale data QA a lot quicker and easier. 

However I notice that the definition of what a "day" is in the daily table is from 11pm of the prior date to 11pm of the current date. This seems very non-standard and likely to cause confusion. 

I think the default assumption would be that the "day" should start and end at midnight. However I think an argument could also be made that a functional day starts and ends closer to 1-2AM when most traffic volumes drop to their minimum. This would allow e.g. weekend nightlife type activities to be lumped into a more meaningful unit. So a late "friday night" could extend to 2am, etc. 

I could go either way on that. What would the rationale be for breaking it at 11pm though? Volumes would still be declining and the date hasn't even changed.

**Comment by gabrielwol** [comment]
This flows from the design of aggregate tables `miovision_api.volumes_15min` and `volumes_15min_mvt`, which both start/end at 11pm. 
@radumas I think you mentioned some historical context for this?

**Comment by radumas** [comment]
Thanks @Nate-Wessel for raising. 

The 23 to 23 processing was a holdover from our previous way of processing the data and attempts to determine whether the camera was actually working in a processed hour. That process was using the previous and subsequent hour, so we were holding back the last hour of the day to process it with the next day. 

Since our new method of determining malfunctioning camera, we didn't need to keep this, but did, for some reason (change is hard).

I don't really see a reason:
1. to keep processing 23-23
2. for the daily table to have the same time bounds 

Though I do now see a logic in generating the daily right after aggregation so we should probably resolve the 15-minute aggregation so we don't build more technical debt on top of it.

**Comment by gabrielwol** [comment]
I can work on this after #735 is merged.
